attributes:
  LastSwiftUpdateCheck: 1010
  LastUpgradeCheck: 1010
  ORGANIZATIONNAME: HIromu
configs:
  Debug: debug
  Develop: debug
  Release: release
schemes:
  MailerTestAppDebug:
    build:
      targets:
        MailerTestApp: all
        MailerTestAppTests: [test]
        MailerTestAppUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
  MailerTestAppDevelop:
    build:
      targets:
        MailerTestApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
  MailerTestAppRelease:
    build:
      targets:
        MailerTestApp: all
    run:
      config: Release
    test:
      config: Release
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release
name: MailerTestApp
options:
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
settingGroups:
  Debug:
    ALWAYS_SEARCH_USER_PATHS: NO
    CLANG_ANALYZER_NONNULL: YES
    CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: YES_AGGRESSIVE
    CLANG_CXX_LANGUAGE_STANDARD: gnu++14
    CLANG_CXX_LIBRARY: libc++
    CLANG_ENABLE_MODULES: YES
    CLANG_ENABLE_OBJC_ARC: YES
    CLANG_ENABLE_OBJC_WEAK: YES
    CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
    CLANG_WARN_BOOL_CONVERSION: YES
    CLANG_WARN_COMMA: YES
    CLANG_WARN_CONSTANT_CONVERSION: YES
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
    CLANG_WARN_DOCUMENTATION_COMMENTS: YES
    CLANG_WARN_EMPTY_BODY: YES
    CLANG_WARN_ENUM_CONVERSION: YES
    CLANG_WARN_INFINITE_RECURSION: YES
    CLANG_WARN_INT_CONVERSION: YES
    CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
    CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
    CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
    CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
    CLANG_WARN_STRICT_PROTOTYPES: YES
    CLANG_WARN_SUSPICIOUS_MOVE: YES
    CLANG_WARN_UNGUARDED_AVAILABILITY: YES_AGGRESSIVE
    CLANG_WARN_UNREACHABLE_CODE: YES
    CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
    CODE_SIGN_IDENTITY: iPhone Developer
    COPY_PHASE_STRIP: NO
    DEBUG_INFORMATION_FORMAT: dwarf
    ENABLE_STRICT_OBJC_MSGSEND: YES
    ENABLE_TESTABILITY: YES
    GCC_C_LANGUAGE_STANDARD: gnu11
    GCC_DYNAMIC_NO_PIC: NO
    GCC_NO_COMMON_BLOCKS: YES
    GCC_OPTIMIZATION_LEVEL: 0
    GCC_PREPROCESSOR_DEFINITIONS:
    - DEBUG=1
    - $(inherited)
    GCC_WARN_64_TO_32_BIT_CONVERSION: YES
    GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
    GCC_WARN_UNDECLARED_SELECTOR: YES
    GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
    GCC_WARN_UNUSED_FUNCTION: YES
    GCC_WARN_UNUSED_VARIABLE: YES
    IPHONEOS_DEPLOYMENT_TARGET: 12.1
    MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
    MTL_FAST_MATH: YES
    ONLY_ACTIVE_ARCH: YES
    SDKROOT: iphoneos
    SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    SWIFT_OPTIMIZATION_LEVEL: -Onone
  Develop:
    ALWAYS_SEARCH_USER_PATHS: NO
    CLANG_ANALYZER_NONNULL: YES
    CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: YES_AGGRESSIVE
    CLANG_CXX_LANGUAGE_STANDARD: gnu++14
    CLANG_CXX_LIBRARY: libc++
    CLANG_ENABLE_MODULES: YES
    CLANG_ENABLE_OBJC_ARC: YES
    CLANG_ENABLE_OBJC_WEAK: YES
    CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
    CLANG_WARN_BOOL_CONVERSION: YES
    CLANG_WARN_COMMA: YES
    CLANG_WARN_CONSTANT_CONVERSION: YES
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
    CLANG_WARN_DOCUMENTATION_COMMENTS: YES
    CLANG_WARN_EMPTY_BODY: YES
    CLANG_WARN_ENUM_CONVERSION: YES
    CLANG_WARN_INFINITE_RECURSION: YES
    CLANG_WARN_INT_CONVERSION: YES
    CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
    CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
    CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
    CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
    CLANG_WARN_STRICT_PROTOTYPES: YES
    CLANG_WARN_SUSPICIOUS_MOVE: YES
    CLANG_WARN_UNGUARDED_AVAILABILITY: YES_AGGRESSIVE
    CLANG_WARN_UNREACHABLE_CODE: YES
    CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
    CODE_SIGN_IDENTITY: iPhone Developer
    COPY_PHASE_STRIP: NO
    DEBUG_INFORMATION_FORMAT: dwarf
    ENABLE_STRICT_OBJC_MSGSEND: YES
    ENABLE_TESTABILITY: YES
    GCC_C_LANGUAGE_STANDARD: gnu11
    GCC_DYNAMIC_NO_PIC: NO
    GCC_NO_COMMON_BLOCKS: YES
    GCC_OPTIMIZATION_LEVEL: 0
    GCC_PREPROCESSOR_DEFINITIONS:
    - DEBUG=1
    - $(inherited)
    GCC_WARN_64_TO_32_BIT_CONVERSION: YES
    GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
    GCC_WARN_UNDECLARED_SELECTOR: YES
    GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
    GCC_WARN_UNUSED_FUNCTION: YES
    GCC_WARN_UNUSED_VARIABLE: YES
    IPHONEOS_DEPLOYMENT_TARGET: 12.1
    MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
    MTL_FAST_MATH: YES
    ONLY_ACTIVE_ARCH: YES
    SDKROOT: iphoneos
    SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    SWIFT_OPTIMIZATION_LEVEL: -Onone
  Release:
    ALWAYS_SEARCH_USER_PATHS: NO
    CLANG_ANALYZER_NONNULL: YES
    CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: YES_AGGRESSIVE
    CLANG_CXX_LANGUAGE_STANDARD: gnu++14
    CLANG_CXX_LIBRARY: libc++
    CLANG_ENABLE_MODULES: YES
    CLANG_ENABLE_OBJC_ARC: YES
    CLANG_ENABLE_OBJC_WEAK: YES
    CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
    CLANG_WARN_BOOL_CONVERSION: YES
    CLANG_WARN_COMMA: YES
    CLANG_WARN_CONSTANT_CONVERSION: YES
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
    CLANG_WARN_DOCUMENTATION_COMMENTS: YES
    CLANG_WARN_EMPTY_BODY: YES
    CLANG_WARN_ENUM_CONVERSION: YES
    CLANG_WARN_INFINITE_RECURSION: YES
    CLANG_WARN_INT_CONVERSION: YES
    CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
    CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
    CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
    CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
    CLANG_WARN_STRICT_PROTOTYPES: YES
    CLANG_WARN_SUSPICIOUS_MOVE: YES
    CLANG_WARN_UNGUARDED_AVAILABILITY: YES_AGGRESSIVE
    CLANG_WARN_UNREACHABLE_CODE: YES
    CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
    CODE_SIGN_IDENTITY: iPhone Developer
    COPY_PHASE_STRIP: NO
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    ENABLE_NS_ASSERTIONS: NO
    ENABLE_STRICT_OBJC_MSGSEND: YES
    GCC_C_LANGUAGE_STANDARD: gnu11
    GCC_NO_COMMON_BLOCKS: YES
    GCC_WARN_64_TO_32_BIT_CONVERSION: YES
    GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
    GCC_WARN_UNDECLARED_SELECTOR: YES
    GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
    GCC_WARN_UNUSED_FUNCTION: YES
    GCC_WARN_UNUSED_VARIABLE: YES
    IPHONEOS_DEPLOYMENT_TARGET: 12.1
    MTL_ENABLE_DEBUG_INFO: NO
    MTL_FAST_MATH: YES
    SDKROOT: iphoneos
    SWIFT_COMPILATION_MODE: wholemodule
    SWIFT_OPTIMIZATION_LEVEL: -O
    VALIDATE_PRODUCT: YES
targets:
  MailerTestApp:
    dependencies:
    - sdk: MessageUI.framework
    platform: iOS
    settings:
      configs:
        Debug:
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: MailerTestApp/Info.plist
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          PRODUCT_BUNDLE_IDENTIFIER: com.crane.MailerTestApp
          PRODUCT_NAME: $(TARGET_NAME)
          SWIFT_VERSION: 4.2
          TARGETED_DEVICE_FAMILY: 1,2
        Develop:
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: MailerTestApp/Info.plist
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          PRODUCT_BUNDLE_IDENTIFIER: com.crane.MailerTestApp
          PRODUCT_NAME: $(TARGET_NAME)
          SWIFT_VERSION: 4.2
          TARGETED_DEVICE_FAMILY: 1,2
        Release:
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: MailerTestApp/Info.plist
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          PRODUCT_BUNDLE_IDENTIFIER: com.crane.MailerTestApp
          PRODUCT_NAME: $(TARGET_NAME)
          SWIFT_VERSION: 4.2
          TARGETED_DEVICE_FAMILY: 1,2
    sources:
    - name: MailerTestApp
      path: MailerTestApp
    type: application
  MailerTestAppTests:
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: MailerTestAppTests/Info.plist
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          - '@loader_path/Frameworks'
          PRODUCT_BUNDLE_IDENTIFIER: com.crane.MailerTestAppTests
          PRODUCT_NAME: $(TARGET_NAME)
          SWIFT_VERSION: 4.2
          TARGETED_DEVICE_FAMILY: 1,2
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/MailerTestApp.app/MailerTestApp
        Develop:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: MailerTestAppTests/Info.plist
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          - '@loader_path/Frameworks'
          PRODUCT_BUNDLE_IDENTIFIER: com.crane.MailerTestAppTests
          PRODUCT_NAME: $(TARGET_NAME)
          SWIFT_VERSION: 4.2
          TARGETED_DEVICE_FAMILY: 1,2
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/MailerTestApp.app/MailerTestApp
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: MailerTestAppTests/Info.plist
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          - '@loader_path/Frameworks'
          PRODUCT_BUNDLE_IDENTIFIER: com.crane.MailerTestAppTests
          PRODUCT_NAME: $(TARGET_NAME)
          SWIFT_VERSION: 4.2
          TARGETED_DEVICE_FAMILY: 1,2
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/MailerTestApp.app/MailerTestApp
    sources:
    - name: MailerTestAppTests
      path: MailerTestAppTests
    type: bundle.unit-test
  MailerTestAppUITests:
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: MailerTestAppUITests/Info.plist
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          - '@loader_path/Frameworks'
          PRODUCT_BUNDLE_IDENTIFIER: com.crane.MailerTestAppUITests
          PRODUCT_NAME: $(TARGET_NAME)
          SWIFT_VERSION: 4.2
          TARGETED_DEVICE_FAMILY: 1,2
          TEST_TARGET_NAME: MailerTestApp
        Develop:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: MailerTestAppUITests/Info.plist
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          - '@loader_path/Frameworks'
          PRODUCT_BUNDLE_IDENTIFIER: com.crane.MailerTestAppUITests
          PRODUCT_NAME: $(TARGET_NAME)
          SWIFT_VERSION: 4.2
          TARGETED_DEVICE_FAMILY: 1,2
          TEST_TARGET_NAME: MailerTestApp
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: MailerTestAppUITests/Info.plist
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          - '@loader_path/Frameworks'
          PRODUCT_BUNDLE_IDENTIFIER: com.crane.MailerTestAppUITests
          PRODUCT_NAME: $(TARGET_NAME)
          SWIFT_VERSION: 4.2
          TARGETED_DEVICE_FAMILY: 1,2
          TEST_TARGET_NAME: MailerTestApp
    sources:
    - name: MailerTestAppUITests
      path: MailerTestAppUITests
    type: bundle.ui-testing
